# Copyright (C) 2026 Ben Asselstine
# This file is licensed under the terms of the GNU GPL version 3 or later.
SUBDIRS=editor
EXTRA_DIST=\
lw.css \
main-prefs.ui \
new-net-game.ui \
army-awarded-medal.ui \
army-bonus.ui \
buy-production.ui \
characters.ui \
city-defeated.ui \
city-looted.ui \
city-pillaged.ui \
city-sacked.ui \
city.ui \
commentator.ui \
destination.ui \
diplomacy-report.ui \
diplomacy.ui \
disband-stack.ui \
fight-order.ui \
game-loaded.ui \
game-lobby.ui \
game-options.ui \
game-over.ui \
setup-new-game.ui \
gold-stolen.ui \
hero-brings-allies.ui \
hero-gains-level.ui \
hero-levels.ui \
hero-offer.ui \
hero.ui \
history-report.ui \
item-bonus.ui \
item-report.ui \
choose-scenario.ui \
main-prefs.ui \
military-advisor.ui \
new-net-game.ui \
add-profile.ui \
new-connection.ui \
new-random-map.ui \
next-turn.ui \
join-game.ui \
player-died.ui \
player-resign.ui \
player-resign-completed.ui \
preferences.ui \
quest-assigned.ui \
quest-completed.ui \
quest-expired.ui \
quest-report.ui \
report.ui \
ruinfight-finished.ui \
ruinfight-started.ui \
ruin-report.ui \
ruin-searched.ui \
sage.ui \
scenario-info.ui \
ships-sunk.ui \
signpost-change.ui \
stack-info.ui \
surrender-refused.ui \
surrender-accepted.ui \
surrender.ui \
search-temple.ui \
treachery.ui \
triumphs.ui \
use-item-on-city.ui \
use-item-on-player.ui \
use-item.ui \
status-box.ui \
stack-tile-box.ui \
stack-army-button.ui \
city-rename.ui \
city-raze.ui \
city-razed.ui \
bags-picked-up.ui \
worms-killed.ui \
bridge-burned.ui \
keeper-captured.ui \
monster-summoned.ui \
mp-added-to-hero-stack.ui \
city-defended.ui \
city-diseased.ui \
city-persuaded.ui \
stack-teleported.ui \
profile-manager.ui
