# Copyright (C) 2026 Ben Asselstine
# This file is licensed under the terms of the GNU GPL version 3 or later.
MAINTAINERCLEANFILES= Makefile.in

musicdir = $(pkgdatadir)/music
music_DATA = \
	back1.ogg \
	defeat.ogg \
	victory.ogg \
	hero.ogg \
	intro.ogg \
	battle.ogg \
        bless.ogg \
	music.xml

EXTRA_DIST = \
	README \
	back1.ogg \
	defeat.ogg \
	victory.ogg \
	hero.ogg \
	intro.ogg \
	battle.ogg \
        bless.ogg \
	music.xml
