SUBDIRS=
EXTRA_DIST=\
armyset-info.ui \
backpack-editor.ui \
battle-calculator.ui \
city-editor.ui \
cityset-info.ui \
fight-order-editor.ui \
hero-editor.ui \
character-editor.ui \
image-editor.ui \
item-editor.ui \
itemlist.ui \
keeper.ui \
map-info.ui \
media.ui \
new-map.ui \
planted-standard-editor.ui \
players.ui \
reward-editor.ui \
reward-list.ui \
ruin-editor.ui \
select-army.ui \
select-character.ui \
select-hidden-ruin.ui \
select-item.ui \
shieldset-info.ui \
signpost-editor.ui \
stack-editor.ui \
switch-sets.ui \
masked-image-editor.ui \
temple-editor.ui \
tile-preview.ui \
tileset-info.ui \
tilestyles.ui \
validation.ui \
tartan-preview.ui \
armies-preview.ui \
item-bonus-editor.ui \
select-strategy.ui \
starting-items.ui \
randomize.ui
