# Copyright (C) 2009, 2010, 2011, 2015, 2017, 2021, 2026 Ben Asselstine
# This file is licensed under the terms of the GNU GPL version 3 or later.

# startup-tools.cpp startup-tools.h 
# startup-editor.cpp startup-editor.h 
bin_PROGRAMS=lw
lw_SOURCES = \
	main.cpp \
	lw.cpp lw.h \
	startup.cpp startup.h \
	\
	action.cpp action.h \
	advertised-game.cpp advertised-game.h \
	ai-allocation.cpp ai-allocation.h \
	ai-analysis.cpp ai-analysis.h \
	ai-city-info.cpp ai-city-info.h \
	ai-diplomacy.cpp ai-diplomacy.h \
	ai-dummy.cpp ai-dummy.h \
	ai-fast.cpp ai-fast.h \
	ai-smart.cpp ai-smart.h \
	army-base.cpp army-base.h \
	army.cpp army.h \
	army-map.cpp army-map.h \
	army-prod-base.cpp  army-prod-base.h \
	army-proto-base.cpp army-proto-base.h \
	army-proto.cpp army-proto.h \
	army-set.cpp army-set.h \
	army-set-list.cpp army-set-list.h \
	backpack.cpp backpack.h \
	boon.cpp boon.h \
	boon-list.cpp boon-list.h \
	box-compose.h \
	bridge.cpp bridge.h \
	bridge-list.cpp bridge-list.h \
	callback-enums.h \
	character.cpp character.h \
	chat-client.cpp chat-client.h \
	city.cpp city.h \
	city-list.cpp city-list.h \
	city-map.cpp city-map.h  \
	city-set.cpp city-set.h \
	city-set-list.cpp city-set-list.h \
	commentator.cpp commentator.h \
	configuration.cpp configuration.h \
	connection-manager.cpp connection-manager.h \
	counter.cpp counter.h \
	create-scenario.cpp create-scenario.h \
	create-scenario-randomize.cpp create-scenario-randomize.h \
	defs.h \
	fight.cpp fight.h \
	fight-result.h \
	file-compat.cpp file-compat.h \
	file.cpp file.h \
	fog-map.cpp fog-map.h \
	game.cpp game.h \
	game-action-list.cpp game-action-list.h \
	game-client.cpp game-client.h \
	game-client-decoder.cpp game-client-decoder.h \
	game-host-client.cpp game-host-client.h \
	game-host-client-tool.h \
	game-list-client.cpp game-list-client.h \
	game-list-client-tool.h \
	game-list.cpp game-list.h \
	game-map.cpp game-map.h \
	game-scenario.cpp game-scenario.h \
	game-scenario-options.cpp game-scenario-options.h \
	game-host-server.h \
	game-list-server.h \
	game-parameters.h \
	game-server.cpp game-server.h \
	game-station.cpp game-station.h \
	hero.cpp hero.h \
	heroes-map.cpp heroes-map.h \
	hero-map.cpp hero-map.h \
	hero-proto.cpp hero-proto.h \
	hero-strategy.cpp hero-strategy.h \
	hero-templates.cpp hero-templates.h \
	history.cpp history.h \
	history-map.cpp history-map.h \
	hosted-game.cpp hosted-game.h \
	image-cache.cpp image-cache.h \
	image-helpers.h image-helpers.cpp \
	immovable.cpp immovable.h \
	import.cpp import.h \
	input-events.h input-events.cpp \
	item.cpp item.h \
	item-list.cpp item-list.h \
	item-map.cpp item-map.h \
	item-proto.cpp item-proto.h \
	keeper.cpp keeper.h \
	lobby.h \
	location-box.cpp location-box.h \
	location.cpp location.h \
	location-list.h \
	map-backpack.cpp map-backpack.h \
	map-generator.cpp map-generator.h \
	map-renderer.cpp map-renderer.h  \
	map-tile.cpp map-tile.h \
	map-tip-position.h  \
	movable.cpp movable.h \
	move-result.cpp move-result.h \
	named.cpp named.h \
	named-location.cpp named-location.h \
	name-list.cpp name-list.h \
	network-action.cpp network-action.h \
	network-common.h \
	network-connection.cpp network-connection.h \
	network-ghs-common.h \
	network-gls-common.h \
	network-history.cpp network-history.h \
	network-player.cpp network-player.h \
	network-server.cpp network-server.h \
	next-turn.cpp next-turn.h \
	next-turn-hotseat.cpp next-turn-hotseat.h \
	next-turn-networked.cpp next-turn-networked.h \
	overview-map.cpp overview-map.h \
	owner-id.cpp owner-id.h \
	path-calculator.cpp path-calculator.h \
	path.cpp path.h \
	pixmask-cache.h \
	pixmask.cpp pixmask.h \
	player.cpp player.h \
	player-list.cpp player-list.h \
	port.cpp port.h \
	port-list.cpp port-list.h \
	positioned.cpp positioned.h \
	prod-slot.cpp prod-slot.h \
	prod-slot-list.cpp prod-slot-list.h \
	profile.cpp profile.h \
	profile-list.cpp profile-list.h \
	quest-city-occupy.cpp quest-city-occupy.h \
	quest-city-raze.cpp quest-city-raze.h \
	quest-city-sack.cpp quest-city-sack.h \
	quest-enemy-armies.cpp quest-enemy-armies.h \
	quest-enemy-army-type.cpp quest-enemy-army-type.h \
	quest-kill-hero.cpp quest-kill-hero.h \
	quest-pillage-gold.cpp quest-pillage-gold.h \
	quest.cpp quest.h \
	quest-map.cpp quest-map.h \
	quest-manager.cpp quest-manager.h \
	real-player.cpp real-player.h \
	recently-played-game.cpp recently-played-game.h \
	recently-played-game-list.cpp recently-played-game-list.h \
	rectangle.h \
	renamable.h \
	reward.cpp reward.h \
	reward-list.cpp reward-list.h \
	rnd.cpp rnd.h \
	road.cpp road.h \
	road-list.cpp road-list.h \
	road-path-calculator.cpp road-path-calculator.h \
	ruin.cpp ruin.h \
	ruin-list.cpp ruin-list.h \
	ruin-map.cpp ruin-map.h \
	sage.cpp sage.h \
	sage-map.cpp sage-map.h \
	scenario-details.cpp scenario-details.h \
	scenario-list.cpp scenario-list.h \
	scenario-media.cpp scenario-media.h \
	select-city-map.cpp select-city-map.h \
	set.cpp set.h\
	set-list.h \
	shield.cpp shield.h \
	shield-set.cpp shield-set.h \
	shield-set-list.cpp shield-set-list.h \
	shield-style.cpp shield-style.h \
	sidebar-stats.h \
	sight-map.cpp sight-map.h \
	signpost.cpp signpost.h \
	signpost-list.cpp signpost-list.h \
	small-map.cpp small-map.h \
	small-tile.cpp small-tile.h \
	snd.cpp snd.h \
	stack.cpp stack.h \
	stack-list.cpp stack-list.h  \
	stack-ref-list.cpp stack-ref-list.h \
	stack-tile.cpp stack-tile.h \
	stone.cpp stone.h \
	stone-list.cpp stone-list.h \
	tar-file.cpp tar-file.h \
	tar-file-image.cpp tar-file-image.h \
	tar-file-masked-image.cpp tar-file-masked-image.h \
	tar-file-sound.cpp tar-file-sound.h \
	tar-helper.cpp tar-helper.h \
	tartan.cpp tartan.h \
	temple.cpp temple.h \
	temple-list.cpp temple-list.h \
	threat.cpp threat.h \
	threat-list.cpp threat-list.h \
	tile.cpp tile.h \
	tile-set.cpp tile-set.h \
	tile-set-list.cpp tile-set-list.h \
	tile-style.cpp tile-style.h \
	tile-style-set.cpp tile-style-set.h \
	triumphs.cpp triumphs.h \
	turn-action-list.cpp turn-action-list.h \
	ucompose.hpp \
	uniquely-identified.cpp uniquely-identified.h \
	vectored-unit.cpp vectored-unit.h \
	vectored-unit-list.cpp vectored-unit-list.h \
	vector.h \
	vector-map.cpp vector-map.h \
	xml-helper.cpp xml-helper.h \
	\
	ui/about-dialog.h \
	ui/add-profile-dialog.h \
	ui/army-awarded-medal-dialog.h \
	ui/army-bonus-dialog.h \
	ui/army-info-tip.h \
	ui/bags-picked-up-dialog.h \
	ui/bar-chart.h \
	ui/bridge-burned-dialog.h \
	ui/buy-production-dialog.h \
	ui/characters-dialog.h \
	ui/choose-scenario-dialog.h \
	ui/city-defeated-dialog.h \
	ui/city-defended-dialog.h \
	ui/city-dialog.h \
	ui/city-diseased-dialog.h \
	ui/city-info-tip.h \
	ui/city-looted-dialog.h \
	ui/city-persuaded-dialog.h \
	ui/city-pillaged-dialog.h \
	ui/city-razed-dialog.h \
	ui/city-raze-dialog.h \
	ui/city-rename-dialog.h \
	ui/city-sacked-dialog.h \
	ui/commentator-dialog.h \
	ui/destination-dialog.h \
	ui/diplomacy-dialog.h \
	ui/diplomacy-report-dialog.h \
	ui/fight-order-dialog.h \
	ui/fight-window.h \
	ui/game-button-box.h \
	ui/game-loaded-dialog.h \
	ui/game-options-dialog.h \
	ui/game-over-dialog.h \
	ui/game-window.h \
	ui/gold-stolen-dialog.h \
	ui/hero-brings-allies-dialog.h \
	ui/hero-dialog.h \
	ui/hero-gains-level-dialog.h \
	ui/hero-levels-dialog.h \
	ui/hero-offer-dialog.h \
	ui/history-report-dialog.h \
	ui/info-tip.h \
	ui/item-bonus-dialog.h \
	ui/item-report-dialog.h \
	ui/join-game-dialog.h \
	ui/new-connection-dialog.h \
	ui/keeper-captured-dialog.h \
	ui/line-chart.h \
	ui/lw-combo.h \
	ui/lw-dialog-base.h  \
	ui/lw-dialog.h \
	ui/main-preferences-dialog.h \
	ui/map-info-tip.h \
	ui/map-info-tip.h \
	ui/map-widget.cpp ui/map-widget.h \
	ui/military-advisor-dialog.h \
	ui/monster-summoned-dialog.h \
	ui/mp-added-to-hero-stack-dialog.h \
	ui/new-net-game-dialog.h \
	ui/new-random-map-dialog.h \
	ui/next-turn-dialog.h \
	ui/player-died-dialog.h \
	ui/preferences-dialog.h \
	ui/profile-manager-dialog.h \
	ui/quest-assigned-dialog.h \
	ui/quest-completed-dialog.h \
	ui/quest-expired-dialog.h \
	ui/quest-report-dialog.h \
	ui/report-dialog.h \
	ui/resign-completed-dialog.h \
	ui/resign-dialog.h \
	ui/ruin-fight-dialog.h \
	ui/ruin-fight-finished-dialog.h \
	ui/ruin-report-dialog.h \
	ui/ruin-searched-dialog.h \
	ui/sage-dialog.h \
	ui/search-temple-dialog.h \
	ui/setup-new-game-dialog.h \
	ui/ships-sunk-dialog.h \
	ui/signpost-change-dialog.h \
	ui/splash-window.h \
	ui/stack-army-button.h \
	ui/stack-disband-dialog.h \
	ui/stack-info-dialog.h \
	ui/stack-info-tip.h \
	ui/stack-teleported-dialog.h \
	ui/stack-tile-box.h \
	ui/status-box.h \
	ui/surrender-accepted-dialog.h \
	ui/surrender-dialog.h \
	ui/surrender-refused-dialog.h \
	ui/tartan-progress-bar.h \
	ui/treachery-dialog.h \
	ui/turn-indicator.h \
	ui/use-item-dialog.h \
	ui/use-item-on-city-dialog.h \
	ui/use-item-on-player-dialog.h \
	ui/worms-killed-dialog.h \
	ui/triumphs-dialog.h \
	ui/lw-column.h \
	ui/game-lobby-dialog.h \
	ui/network-game-download-window.h \
	ui/scenario-info-dialog.h \
	\
	editor/undo-mgr.h \
	editor/undo-action.h \
	editor/cityset-undo.h \
	editor/editor-undo-actions.h \
	editor/image-undo-actions.h \
	editor/item-list-undo-actions.h \
	editor/masked-image-undo-actions.h \
	editor/cityset-info-undo-actions.h \
	editor/shieldset-info-undo-actions.h \
	editor/map-info-undo-actions.h \
	editor/shieldset-undo.h \
	editor/armyset-undo.h \
	editor/armyset-info-undo-actions.h \
	editor/tileset-undo.h \
	editor/tileset-info-undo-actions.h \
	editor/tilestyles-undo.h \
	editor/backpack-editor-undo-actions.h \
	editor/item-bonus-editor-undo-actions.h \
	editor/item-editor-undo-actions.h \
	editor/hero-editor-undo-actions.h \
	editor/battle-calculator-undo-actions.h \
	editor/new-map-undo-actions.h \
	editor/switch-sets-undo-actions.h \
	editor/players-undo-actions.h \
	editor/character-undo-actions.h \
	editor/starting-items-undo-actions.h \
	editor/smallmap-editor-undo-actions.h \
	editor/planted-standard-undo-actions.h \
	editor/signpost-undo-actions.h \
	editor/temple-editor-undo-actions.h \
	editor/media-undo-actions.h \
	editor/fight-order-undo-actions.h \
	editor/ruin-undo-actions.h \
	editor/keeper-undo-actions.h \
	editor/reward-undo-actions.h \
	editor/stack-undo-actions.h \
	editor/city-undo-actions.h \
	editor/reward-list-undo-actions.h \
	\
	editor/file-filter.h \
	editor/file-label.h \
	editor/button-label.h \
	editor/army-type-label.h \
	editor/scenario.h \
	\
	editor/cityset-window.h \
	editor/image-editor-dialog.h \
	editor/masked-image-editor-dialog.h \
	editor/cityset-info-dialog.h \
	editor/shieldset-info-dialog.h \
	editor/shieldset-window.h \
	editor/preview-tartan-progress-bar.h \
	editor/tartan-preview-dialog.h \
	editor/armyset-window.h \
	editor/armyset-info-dialog.h \
	editor/armies-preview-dialog.h \
	editor/tileset-window.h \
	editor/tileset-info-dialog.h \
	editor/tilestyles-dialog.h \
	editor/tile-preview-dialog.h \
	editor/tile-preview-scene.h \
	editor/scenario-builder-window.h \
	editor/editor-splash-window.h \
	editor/editor-load-window.h \
	editor/map-info-dialog.h \
	editor/editor-map-widget.cpp editor/editor-map-widget.h \
	editor/item-list-dialog.h \
	editor/select-army-dialog.h \
	editor/backpack-editor-dialog.h \
	editor/item-bonus-editor-dialog.h \
	editor/item-editor-dialog.h \
	editor/hero-editor-dialog.h \
	editor/select-character-dialog.h \
	editor/battle-calculator-dialog.h \
	editor/new-map-dialog.h \
	editor/switch-sets-dialog.h \
	editor/players-dialog.h \
	editor/character-editor-dialog.h \
	editor/select-strategy-dialog.h \
	editor/starting-items-dialog.h \
	editor/select-item-dialog.h \
	editor/pointer-size-menu-button.h \
	editor/shield-menu-button.h \
	editor/smallmap-editor-window.h \
	editor/editable-small-map.cpp editor/editable-small-map.h \
	editor/planted-standard-editor-dialog.h \
	editor/select-tilestyle-popover.h \
	editor/select-stone-popover.h \
	editor/select-road-popover.h \
	editor/signpost-editor-dialog.h \
	editor/temple-editor-dialog.h \
	editor/media-dialog.h \
	editor/fight-order-editor-dialog.h \
	editor/ruin-editor-dialog.h \
	editor/keeper-editor-dialog.h \
	editor/select-hidden-ruin-dialog.h \
	editor/reward-editor-dialog.h \
	editor/stack-editor-dialog.h \
	editor/city-editor-dialog.h \
	editor/reward-list-editor-dialog.h \
	editor/validation-dialog.h \
	editor/randomize-dialog.h

nodist_lw_SOURCES = resources.c

BUILT_SOURCES = resources.c
CLEANFILES = resources.c

resource_files=\
../data/ui/add-profile.ui \
../data/ui/army-awarded-medal.ui \
../data/ui/army-bonus.ui \
../data/ui/bags-picked-up.ui \
../data/ui/bridge-burned.ui \
../data/ui/buy-production.ui \
../data/ui/characters.ui \
../data/ui/choose-scenario.ui \
../data/ui/city-defeated.ui \
../data/ui/city-defended.ui \
../data/ui/city-diseased.ui \
../data/ui/city-looted.ui \
../data/ui/city-persuaded.ui \
../data/ui/city-pillaged.ui \
../data/ui/city-razed.ui \
../data/ui/city-raze.ui \
../data/ui/city-rename.ui \
../data/ui/city-sacked.ui \
../data/ui/city.ui \
../data/ui/commentator.ui \
../data/ui/destination.ui \
../data/ui/diplomacy-report.ui \
../data/ui/diplomacy.ui \
../data/ui/disband-stack.ui \
../data/ui/fight-order.ui \
../data/ui/game-loaded.ui \
../data/ui/game-lobby.ui \
../data/ui/game-options.ui \
../data/ui/game-over.ui \
../data/ui/gold-stolen.ui \
../data/ui/hero-brings-allies.ui \
../data/ui/hero-gains-level.ui \
../data/ui/hero-levels.ui \
../data/ui/hero-offer.ui \
../data/ui/hero.ui \
../data/ui/history-report.ui \
../data/ui/item-bonus.ui \
../data/ui/item-report.ui \
../data/ui/join-game.ui \
../data/ui/new-connection.ui \
../data/ui/keeper-captured.ui \
../data/ui/lw.css \
../data/ui/main-prefs.ui \
../data/ui/military-advisor.ui \
../data/ui/monster-summoned.ui \
../data/ui/mp-added-to-hero-stack.ui \
../data/ui/new-net-game.ui \
../data/ui/new-random-map.ui \
../data/ui/next-turn.ui \
../data/ui/player-died.ui \
../data/ui/player-resign-completed.ui \
../data/ui/player-resign.ui \
../data/ui/preferences.ui \
../data/ui/profile-manager.ui \
../data/ui/quest-assigned.ui \
../data/ui/quest-completed.ui \
../data/ui/quest-expired.ui \
../data/ui/quest-report.ui \
../data/ui/report.ui \
../data/ui/ruinfight-finished.ui \
../data/ui/ruinfight-started.ui \
../data/ui/ruin-report.ui \
../data/ui/ruin-searched.ui \
../data/ui/sage.ui \
../data/ui/scenario-info.ui \
../data/ui/search-temple.ui \
../data/ui/setup-new-game.ui \
../data/ui/ships-sunk.ui \
../data/ui/signpost-change.ui \
../data/ui/stack-army-button.ui \
../data/ui/stack-info.ui \
../data/ui/stack-teleported.ui \
../data/ui/stack-tile-box.ui \
../data/ui/status-box.ui \
../data/ui/surrender-accepted.ui \
../data/ui/surrender-refused.ui \
../data/ui/surrender.ui \
../data/ui/treachery.ui \
../data/ui/triumphs.ui \
../data/ui/use-item-on-city.ui \
../data/ui/use-item-on-player.ui \
../data/ui/use-item.ui \
../data/ui/worms-killed.ui  \
../data/ui/editor/armyset-info.ui \
../data/ui/editor/backpack-editor.ui \
../data/ui/editor/battle-calculator.ui \
../data/ui/editor/city-editor.ui \
../data/ui/editor/cityset-info.ui \
../data/ui/editor/fight-order-editor.ui \
../data/ui/editor/hero-editor.ui \
../data/ui/editor/character-editor.ui \
../data/ui/editor/image-editor.ui \
../data/ui/editor/item-editor.ui \
../data/ui/editor/itemlist.ui \
../data/ui/editor/keeper.ui \
../data/ui/editor/map-info.ui \
../data/ui/editor/media.ui \
../data/ui/editor/new-map.ui \
../data/ui/editor/planted-standard-editor.ui \
../data/ui/editor/players.ui \
../data/ui/editor/reward-editor.ui \
../data/ui/editor/reward-list.ui \
../data/ui/editor/ruin-editor.ui \
../data/ui/editor/select-army.ui \
../data/ui/editor/select-character.ui \
../data/ui/editor/select-hidden-ruin.ui \
../data/ui/editor/select-item.ui \
../data/ui/editor/shieldset-info.ui \
../data/ui/editor/signpost-editor.ui \
../data/ui/editor/stack-editor.ui \
../data/ui/editor/select-strategy.ui \
../data/ui/editor/switch-sets.ui \
../data/ui/editor/masked-image-editor.ui \
../data/ui/editor/temple-editor.ui \
../data/ui/editor/tile-preview.ui \
../data/ui/editor/tileset-info.ui \
../data/ui/editor/tilestyles.ui \
../data/ui/editor/validation.ui \
../data/ui/editor/tartan-preview.ui \
../data/ui/editor/armies-preview.ui \
../data/ui/editor/starting-items.ui \
../data/ui/editor/randomize.ui

resources.c: ../data/resources.gresource.xml ${resource_files}
	$(AM_V_GEN) $(GLIB_COMPILE_RESOURCES) \
		--target=$@ \
		--sourcedir=$(srcdir)/../data \
		--generate-source \
		$(srcdir)/../data/resources.gresource.xml

lw_CFLAGS = $(GTKMM_CFLAGS)

AM_CXXFLAGS = -std=c++17 -g -Wall -Wextra -Wshadow -O0

AM_CPPFLAGS = \
	-DLOCALEDIR=\""$(localedir)"\" \
	-DGETTEXT_PACKAGE=\""$(GETTEXT_PACKAGE)"\" \
	-DLORDSAWAR_DATADIR='"$(LORDSAWAR_DATADIR)"' \
	$(GTKMM_CFLAGS) \
	-I$(top_srcdir) \
	-I$(top_srcdir)/src/ui \
	-I$(top_srcdir)/src/editor \
	-I$(top_builddir) \
	$(XMLPP_CFLAGS) \
	$(XSLT_CFLAGS) \
	$(GST_CFLAGS) \
	$(ARCHIVE_CFLAGS) \
	$(LIBSIGC_CFLAGS)

lw_LDADD = \
	$(GTKMM_LIBS) \
	$(LIBINTL) \
	$(GST_LIBS) \
	$(XMLPP_LIBS) \
	$(XSLT_LIBS) \
	$(ARCHIVE_LIBS) \
	$(LIBSIGC_LIBS) \
	-lz \
	$(AM_LDADD)
