//  Copyright (C) 2007, 2008, Ole Laursen
//  Copyright (C) 2007, 2008, 2009, 2010, 2011, 2012, 2014, 2015, 2016, 2017,
//  2020, 2021, 2026 Ben Asselstine
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Library General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 31 Milk Street #960789, Boston, MA 02196, USA.

#include <gtkmm.h>
#include "lw.h"
#include "startup.h"
#include "vector.h"
#include "configuration.h"
#include "profile-list.h"
#include "game-parameters.h"
#include "create-scenario-randomize.h"
#include "game-scenario.h"
#include "player-list.h"
#include "game.h"
#include "small-map.h"
#include "next-turn-hotseat.h"
#include "recently-played-game-list.h"
#include "army-set-list.h"
#include "tile-set-list.h"
#include "shield-set-list.h"
#include "city-set-list.h"
#include "choose-scenario-dialog.h"
#include "lw-dialog.h"
#include "setup-new-game-dialog.h"
#include "next-turn-hotseat.h"
#include "next-turn-networked.h"
#include "scenario-details.h"
#include "file-compat.h"

#include "game-lobby-dialog.h"
#include "game-server.h"
#include "game-client.h"
#include "lobby.h"
#include "network-game-download-window.h"
#include "editor-load-window.h"

Startup* Startup::s_instance = NULL;

Startup* Startup::instance ()
{
  if (s_instance == NULL)
    s_instance = new Startup ();

  return s_instance;
}

void Startup::splash ()
{
  initialize ();
  setup_splash_window ();
}

void Startup::server (std::string load_filename)
{
  Lw::loop = Glib::MainLoop::create ();

  auto profile = Profilelist::instance ()->getAdminProfile ();
  if (!profile)
    profile =
      Profilelist::instance ()->findLastPlayedProfileForUser
      (Glib::get_user_name ());
  if (!profile && Profilelist::instance ()->empty () == false)
    profile = Profilelist::instance ()->front ();
  if (!profile && Profilelist::instance ()->empty () == true)
    profile = Profilelist::createAdminProfile ();

  if (load_filename.empty () == true)
    {
      GameParameters g;
      //for (unsigned int i = 0; i < MAX_PLAYERS; i++)
      for (unsigned int i = 0; i < 3; i++)
        {
          GameParameters::Player p;
          p.type = GameParameters::Player::HUMAN;
          p.id = i;
          p.name = CreateScenarioRandomize::getPlayerName (Shield::Color (i)); 
          g.players.push_back (p);
        }
      g.map.width = MAP_SIZE_NORMAL_WIDTH;
      g.map.height = MAP_SIZE_NORMAL_HEIGHT;
      g.map.grass = 78;
      g.map.water = 7;
      g.map.swamp = 2;
      g.map.forest = 3;
      g.map.hills = 5;
      g.map.mountains = 5;
      g.map.cities = 80;
      g.map.ruins = 15;
      g.map.temples = 3;
      g.map.signposts = 20;
      g.map_path = "";
      g.play_with_quests = GameParameters::ONE_QUEST_PER_PLAYER;
      g.hidden_map = false;
      g.neutral_cities = GameParameters::STRONG;
      g.razing_cities = GameParameters::ALWAYS;
      g.diplomacy = false;
      g.random_turns = false;
      g.quick_start = GameParameters::NO_QUICK_START;
      g.intense_combat = false;
      g.military_advisor = false;
      for (guint32 i = 0; i < MAX_PLAYERS + 1; i++)
        g.army_theme[i] = "default";
      g.tile_theme = "default";
      g.shield_theme = "default";
      g.city_theme = "default";
      g.cities_can_produce_allies = false;
      g.cusp_of_war = false;
      g.see_opponents_stacks = false;
      g.see_opponents_production = false;
      g.vectoring_mode = GameParameters::VECTORING_ALWAYS_TWO_TURNS;
      g.build_production_mode = GameParameters::BUILD_PRODUCTION_ALWAYS;
      g.sacking_mode = GameParameters::SACKING_ALWAYS;
      g.difficulty = GameScenario::calculate_difficulty_rating (g);
      g.name = _("Autogenerated");
      g.comment = "This is a randomly generated scenario.";

      std::string path = File::get_tmp_file (MAP_EXT);
      GameScenario::create_and_dump
        (path, g, NULL,
         [this, g, profile, path] ()
         {
           bool broken = false;

           Glib::ustring err = "";
           auto game_scenario = new GameScenario (path, broken, err);
           if (!broken)
             serve (game_scenario, g, Lw::app->m_port ?
                    Lw::app->m_port : LORDSAWAR_PORT, profile, true);
           else
             {
               std::cerr <<
                 String::ucompose (_("%1: could not load `%2'.  %3"),
                                   Lw::get_prgname (), path, err) <<
                 std::endl;
               exit (1);
             }
         });
    }
  else
    {
      bool broken = false;
      GameParameters g = GameScenario::loadGameParameters (load_filename,
                                                           broken);
      if (!broken)
        {
          Glib::ustring err = "";
          auto game_scenario = new GameScenario (load_filename, broken, err);
          if (!broken)
            serve (game_scenario, g, Lw::app->m_port ?
                   Lw::app->m_port : LORDSAWAR_PORT, profile, true);
          else
            {
              std::cerr <<
                String::ucompose (_("%1: could not load `%2'.  %3"),
                                  Lw::get_prgname (), load_filename, err) <<
                std::endl;
              exit (1);
            }
        }
      else
        {
          std::cerr <<
            String::ucompose (_("%1: could not load `%2'."),
                              Lw::get_prgname (), load_filename) <<
            std::endl;
          exit (1);
        }

    } 

  Lw::app->hold ();
  Lw::loop->run ();
}

void Startup::hotseat_game (GameScenario *g)
{
  NextTurn *next_turn = new NextTurnHotseat ();
  setup_game_window (true);
  m_game_window->new_game (g, next_turn);
  m_signal_game_window_coming_up.emit ();
}

void Startup::setup_hotseat_game (Gtk::ApplicationWindow *parent)
{
  auto d = LwDialog::build<ChooseScenarioDialog> (parent);
  d->setup ();
  d->signal_scenario_selected ().connect
    ([this, d] (ScenarioDetails *scen)
     {
       if (scen)
         setup_scenario (scen->get_filename (), GameScenario::HOTSEAT, d);
       else
         {
           //if scenario is null it means we want a random map
           auto dd = LwDialog::build<NewRandomMapDialog> (d);
           dd->setup ();
           dd->signal_scenario_generated ().connect
             ([this, d, dd] (std::string filename, GameScenario::PlayMode m)
              {
                setup_scenario (filename, m, d);
              });
           dd->signal_response ().connect
             ([d] (Gtk::ResponseType resp)
              {
                if (resp != Gtk::ResponseType::ACCEPT)
                  delete d;
                // otherwise this dialog gets deleted when the game window is
                // coming up
              });
         }
     });
  d->signal_response ().connect
    ([d] (Gtk::ResponseType resp)
     {
       if (resp != Gtk::ResponseType::ACCEPT)
         delete d;
       //otherwise we delete when the game window is coming up
     });
}

void Startup::initialize ()
{
  if (m_initialized)
    return;
  if (Lw::app->m_configuration_file_path != "")
    Configuration::s_configuration_file_path = Lw::app->m_configuration_file_path;
  if (Lw::app->m_save_path != "")
    Configuration::s_savePath = Lw::app->m_save_path;
  initialize_configuration ();
  if (Lw::app->m_cacheSize)
    Configuration::s_cacheSize = Lw::app->m_cacheSize;
  Profilelist::support_backward_compatibility ();
  RecentlyPlayedGameList::support_backward_compatibility ();
  Gamelist::support_backward_compatibility ();
  FileCompat::support_backward_compatibility_for_common_files ();
  FileCompat::instance ()->initialize ();
  RecentlyPlayedGameList::instance ()->load ();

  // Check if armysets are in the path (otherwise exit)
  Armysetlist::scan (Armyset::file_extension);
  Tilesetlist::scan (Tileset::file_extension);
  Shieldsetlist::scan (Shieldset::file_extension);
  Citysetlist::scan (Cityset::file_extension);
  m_initialized = true;
}

void Startup::run_stress_test (GameScenario *game_scenario, std::string path)
{
  NextTurnHotseat *nextTurn = new NextTurnHotseat ();

  nextTurn->snextRound.connect
    ([] ()
     {
       static int count = 1;
       count++;
       std::cout <<
         String::ucompose ("%1: starting round %2!",
                           Lw::get_prgname (), count) << std::endl;
     });

  auto game = new Game (game_scenario, nextTurn);

  game->get_smallmap ().set_slide_speed (0);
  Configuration::s_displaySpeedDelay = 0;
  time_t start = time (NULL);
  nextTurn->start ();
  nextTurn->signal_game_over ().connect
    ([game, start, game_scenario, path] ()
     {
       File::erase (path);
       //next turn and game_Scenario get deleted inside game.
       double mins = (time (NULL) - start) / 60.0;
       printf ("seed: %d, duration: %.2lf mins, turns: %d ",
               Lw::app->m_random_number_seed, mins, game_scenario->getRound ());
       printf ("winner type: %s\n",
               Player::playerTypeToString
               (Playerlist::instance ()->getFirstLiving ()->getType ()).c_str ());
       Glib::ustring s =
         File::getTempFile (File::getCacheDir (),
                            String::ucompose ("run-seed-%1",
                                              Lw::app->m_random_number_seed)) +
         SAVE_EXT;
       game_scenario->saveGame (s);
       delete game;

       Lw::quit_loop ();
     });
}

void Startup::stress_test (bool view_stress_test, GameParameters::Player::Type typ, bool viewfast)
{
  initialize ();
  Lw::loop = Glib::MainLoop::create ();
  Glib::signal_idle ().connect
    ([this, view_stress_test, typ, viewfast]()
     {
       GameParameters g;
       GameParameters::Player p;
       for (unsigned int i = 0; i < MAX_PLAYERS; i++)
         {
           p.type = typ;
           p.id = i;
           switch (p.id)
             {
             case 0: p.name = "one"; break;
             case 1: p.name = "two"; break;
             case 2: p.name = "three"; break;
             case 3: p.name = "four"; break;
             case 4: p.name = "five"; break;
             case 5: p.name = "six"; break;
             case 6: p.name = "seven"; break;
             case 7: p.name = "eight"; break;
             }
           g.players.push_back (p);
         }
       g.map.width = MAP_SIZE_NORMAL_WIDTH;
       g.map.height = MAP_SIZE_NORMAL_HEIGHT;
       g.map.grass = 78;
       g.map.water = 7;
       g.map.swamp = 2;
       g.map.forest = 3;
       g.map.hills = 5;
       g.map.mountains = 5;
       g.map.cities = 20;
       g.map.ruins = 15;
       g.map.temples = 3;
       g.map.signposts = 10;
       g.map_path = "";
       g.play_with_quests = GameParameters::ONE_QUEST_PER_PLAYER;
       g.hidden_map = false;
       g.neutral_cities = GameParameters::STRONG;
       g.razing_cities = GameParameters::ALWAYS;
       g.diplomacy = false;
       g.random_turns = false;
       g.quick_start = GameParameters::NO_QUICK_START;
       g.intense_combat = false;
       g.military_advisor = false;
       for (guint32 i = 0; i < MAX_PLAYERS + 1; i++)
         g.army_theme[i] = "default";
       g.tile_theme = "default";
       g.shield_theme = "default";
       g.city_theme = "default";
       g.cities_can_produce_allies = false;
       g.cusp_of_war = false;
       g.see_opponents_stacks = true;
       g.see_opponents_production = true;
       g.vectoring_mode = GameParameters::VECTORING_ALWAYS_TWO_TURNS;
       g.build_production_mode = GameParameters::BUILD_PRODUCTION_ALWAYS;
       g.sacking_mode = GameParameters::SACKING_ALWAYS;
       g.difficulty = GameScenario::calculate_difficulty_rating (g);

       bool broken = false;
       Glib::ustring path;
       path = File::getTempFile (File::getCacheDir (),
                                 File::getRandomlyGeneratedMapFile ());
       GameScenario::create_and_dump (path, g, NULL,
                                      [] ()
                                      {
                                      });
       g.map_path = path;

       if (view_stress_test)
         {
           bool go_fast = viewfast;
           if (go_fast)
             {
               Configuration::s_displaySpeedDelay = 0;
               SmallMap::s_quick = true;
               Configuration::s_displayFightRoundDelayFast = 0;
               Configuration::s_displayFightRoundDelaySlow = 0;
               GameWindow::s_displayBattleExplosionDelay = 0;
               GameWindow::s_displayAbbreviatedBattleExplosionDelay = 0;
               FightWindow::speedy ();
             }
           broken = false;
           Glib::ustring err;
           GameScenario* game_scenario = new GameScenario (path, broken, err);
           if (!broken)
             {
               Configuration::s_autosave_policy = Configuration::NO_AUTOSAVING;
               Playerlist::instance ()->syncPlayers (g);
               game_scenario->initialize (g);
               NextTurn *next_turn = new NextTurnHotseat ();
               next_turn->snextRound.connect
                 ([] ()
                  {
                    static int count = 1;
                    count++;
                    std::cout <<
                      String::ucompose ("%1: starting round %2!",
                                        Lw::get_prgname (), count) << std::endl;
                  });
               time_t start = time (NULL);
               next_turn->signal_game_over ().connect
                 ([start, game_scenario, path] ()
                  {
                    File::erase (path);
                    //next turn and game_Scenario get deleted inside game.
                    double mins = (time (NULL) - start) / 60.0;
                    printf ("seed: %d, duration: %.2lf mins, turns: %d ", 
                            Lw::app->m_random_number_seed, mins,
                            game_scenario->getRound ());
                    auto ptype = Playerlist::getFirstLiving ()->getType ();
                    printf ("winner type: %s\n",
                            Player::playerTypeToString (ptype).c_str ());
                    auto fname = 
                      String::ucompose ("run-seed-%1%2",
                                        Lw::app->m_random_number_seed,
                                        SAVE_EXT);
                    game_scenario->saveGame
                      (File::getTempFile (File::getCacheDir (), fname));

                    Lw::quit_loop ();
                    exit (0); //fixme, this shouldn't be necessary
                  });
               setup_game_window (true);
               m_signal_game_window_coming_up.emit ();
               m_game_window->load_game (game_scenario, next_turn);
             }
           return false;
         }
       Glib::ustring err;
       GameScenario* game_scenario = new GameScenario (g.map_path, broken, err);
       if (broken)
         return false;

       Configuration::s_autosave_policy = Configuration::NO_AUTOSAVING;
       Playerlist::instance ()->syncPlayers (g);
       game_scenario->initialize (g);

       run_stress_test (game_scenario, path);

       return false;
     });

  Lw::app->hold ();
  Lw::loop->run ();
}

void Startup::setup_scenario (std::string map_filename, GameScenario::PlayMode mode, Gtk::Window *parent)
{
  auto d = LwDialog::build<SetupNewGameDialog>(parent);
  d->setup (map_filename, mode);
  d->signal_game_setup ().connect
    ([this, d] (GameScenario *g)
     {
       hotseat_game (g);
     });
  d->signal_response ().connect
    ([d] (Gtk::ResponseType resp)
     {
       if (resp != Gtk::ResponseType::ACCEPT)
         delete d;
       //otherwise we leak?
     });
}

void Startup::test_scenario ()
{
  initialize ();
  SmallMap::s_quick = true;
  // quick load a test scenario
  GameParameters g;
  GameParameters::Player p;
  p.type = GameParameters::Player::HUMAN;
  p.id = 0;
  p.name = "Mr. Test";
  g.players.push_back (p);
  p.type = GameParameters::Player::EASY;
  p.id = 1;
  p.name = "Evil";
  g.players.push_back (p);
  for (unsigned int i = 2; i < MAX_PLAYERS; i++)
    {
      p.type = GameParameters::Player::OFF;
      p.id = i;
      p.name = "";
      g.players.push_back (p);
    }
  //g.map.width = 50;
  //g.map.height = 75;
  //g.map.width = 70;
  //g.map.height = 105;
  g.map.width = 112;
  g.map.height = 156;
  //g.map.width = 125;
  //g.map.height = 125;
  //g.map.width = 255;
  //g.map.height = 255;
  //g.map.width = 500;
  //g.map.height = 500;
  g.map.grass = 78;
  g.map.water = 7;
  g.map.swamp = 2;
  g.map.forest = 3;
  g.map.hills = 5;
  g.map.mountains = 5;
  //g.map.cities = 3;
  g.map.cities = 40;
  //g.map.cities = 80;
  g.map.ruins = 25;
  g.map.temples = 13;
  g.map.signposts = 0;

  g.map_path = "";
  g.tile_theme = "default";
  for (guint32 i = 0; i < MAX_PLAYERS + 1; i++)
    g.army_theme[i] = "default";
  g.shield_theme = "default";
  g.city_theme = "default";

  g.see_opponents_stacks = true;
  g.see_opponents_production = true;
  g.play_with_quests = GameParameters::ONE_QUEST_PER_PLAYER;
  g.hidden_map = false;
  g.diplomacy = false;

  g.neutral_cities = GameParameters::STRONG;
  g.razing_cities = GameParameters::ALWAYS;
  g.quick_start = GameParameters::NO_QUICK_START;
  g.cusp_of_war = false;
  g.intense_combat = false;
  g.military_advisor = false;
  g.random_turns = false;
  g.cities_can_produce_allies = false;
  g.name = "";
  g.comment = "";

  g.difficulty = GameScenario::calculate_difficulty_rating (g);

  Glib::ustring path = File::getTempFile (File::getCacheDir (),
                                          File::getRandomlyGeneratedMapFile ());
  GameScenario::create_and_dump (path, g, NULL,
                                 [] ()
                                 {
                                 });
  g.map_path = path;
  bool broken = false;
  Glib::ustring err;
  GameScenario* game_scenario = new GameScenario (g.map_path, broken, err);
  Playerlist::instance ()->syncPlayers (g);
  game_scenario->initialize (g);
  if (!broken)
    Startup::instance ()->hotseat_game (game_scenario);
}

void Startup::load_saved_game (std::string load_filename)
{
  initialize ();
  bool broken = false;
  Glib::ustring err;
  GameScenario* g = new GameScenario (load_filename, broken, err);
  if (!broken)
    {
      if (g->getPlayMode () == GameScenario::HOTSEAT)
        {
          NextTurn *next_turn = new NextTurnHotseat ();
          setup_game_window (true);
          m_signal_game_window_coming_up.emit ();
          m_game_window->load_game (g, next_turn);
        }
    }
}

void Startup::load_map (std::string load_filename)
{
  splash ();
  setup_scenario (load_filename, GameScenario::HOTSEAT, m_splash_window);
}

void Startup::client (Gtk::ApplicationWindow *parent, Glib::ustring host,
                      unsigned short port, Profile *p)
{
  Lobby::deleteInstance ();
  Lobby::instance ()->set_profile (p->getId ());
  Lobby::instance ()->join (p->getId (), p->getNickname ());
  GameClient::deleteInstance ();
  GameClient *game_client = GameClient::instance ();
  game_client->signal_game_scenario_received ().connect
    ([this, host, port, p, game_client, parent] (std::string path)
     {
       m_download_window->hide ();
       delete m_download_window;
       m_download_window = NULL;
        
       auto w = Gtk::make_managed<EditorLoadWindow> ();
       w->setup ();
       w->present ();
       w->set_modal (true);
       w->set_transient_for (*m_splash_window);

       sigc::connection load_tick_conn;
       load_tick_conn = GameScenario::load_tick.connect
         ([this, w, load_tick_conn] (double fraction) mutable
          {
            if (w)
              {
                w->set_fraction (fraction);
                Lw::do_events ();
              }
            else
              load_tick_conn.disconnect ();
          });
       //a path to our downloaded game scenario
       //the scenario comes over the line pre-initialized
       bool broken = false;
       Glib::ustring err;
       GameScenario* game_scenario = new GameScenario (path, broken, err);
       load_tick_conn.disconnect ();
       delete w;
       w = NULL;
       if (!broken)
         {
           auto recent = RecentlyPlayedGameList::instance ();
           recent->addNetworkedEntry (game_scenario, p, host, port);
           recent->save ();

           broken = false;

           start_game_lobby_for_client (parent, game_scenario);
         }
     });

  game_client->signal_logged_in_as_same_profile_id ().connect
    ([this] ()
     {
       hide_download_window ();
       auto dialog = LwDialog::alert (_("Could not connect"),
                                      _("Same profile id is logged in."));
       dialog->choose
         (*m_splash_window,
          [dialog] (auto result)
          {
            dialog->choose_finish (result);
            return;
          });
     });

  game_client->signal_client_disconnected ().connect
    ([] ()
     {
       GameClient::deleteInstance ();
       Lw::app->quit ();
     });

  game_client->signal_client_forcibly_disconnected ().connect
    ([this] ()
     {
       hide_download_window ();
       if (m_game_lobby_dialog)
         m_game_lobby_dialog->hide ();
       auto dialog = LwDialog::alert (_("Server disconnected"), "");
       dialog->choose
         (*m_splash_window,
          [dialog] (auto result)
          {
            dialog->choose_finish (result);
            return;
          });
     });

  game_client->signal_client_could_not_connect ().connect
    ([this] ()
     {
       hide_download_window ();
       auto dialog = LwDialog::alert (_("Could not connect"),
                                      _("Server could not be contacted."));
       dialog->choose
         (*m_splash_window,
          [dialog] (auto result)
          {
            dialog->choose_finish (result);
            return;
          });
     });

  game_client->signal_client_connected ().connect
    ([this, game_client, parent] ()
     {
       hide_download_window ();
       m_download_window = new NetworkGameDownloadWindow ();
       m_download_window->setup ();
       m_download_window->set_transient_for (*parent);
       m_download_window->present ();

       game_client->signal_payload_progress ().connect
         ([this] (int numerator, int denominator)
          {
            if (!m_download_window)
              return;
            double fraction = (double)numerator / (double)denominator;
            if (fraction < 1)
              m_download_window->set_fraction (fraction);
          });
     });

  game_client->start (host, port, p->getId (), p->getNickname ());
}

void Startup::hide_download_window ()
{
  if (m_download_window)
    delete m_download_window;
  m_download_window = NULL;
}

void Startup::setup_game_window (bool show)
{
  m_game_window = Gtk::make_managed<GameWindow> ();
  Lw::app->add_window (*m_game_window);
  m_game_window->signal_game_ended_start_new ().connect
    ([this, show] ()
     {
       delete m_game_window;
       
       Lw::app->add_window (*m_splash_window);
       if (show)
         m_splash_window->present ();
     });
  m_game_window->signal_show_lobby ().connect
    ([this] ()
     {
       if (m_game_lobby_dialog)
         m_game_lobby_dialog->show ();
     });
       
  if (show)
    m_game_window->show ();
}

void Startup::setup_splash_window ()
{
  m_splash_window = Gtk::make_managed<SplashWindow>();
  Lw::app->add_window (*m_splash_window);
  m_splash_window->present ();
  m_splash_window->signal_setup_hotseat_game ().connect
    ([this] (Gtk::ApplicationWindow *parent)
     {
       setup_hotseat_game (parent);
     });

  m_splash_window->signal_scenario_builder ().connect
    ([this] ()
     {
       m_splash_window->hide ();
       //editor (""); compiletimefix
     });

  m_splash_window->signal_load_game ().connect
    ([this] (Gtk::ApplicationWindow *parent, std::string filename)
     {
       (void) parent;
       load_saved_game (filename);
     });

  m_splash_window->signal_setup_net_client ().connect
    ([this] (Gtk::ApplicationWindow *parent, Glib::ustring host,
             unsigned short port, Profile *profile)
     {
       client (parent, host, port, profile);
     });

  m_splash_window->signal_setup_net_server ().connect
    ([this] (Gtk::ApplicationWindow *parent, Profile *profile)
     {
       server (parent, profile);
     });

  signal_game_window_coming_up ().connect
    ([this] ()
     {
       m_splash_window->hide ();
     });
}

void Startup::serve (GameScenario *game_scenario, GameParameters g, int port,
                     Profile *profile, bool mod_first_participant)
{
  Lobby::deleteInstance ();
  Lobby::instance ()->join (profile->getId (), profile->getNickname ());
  Lobby::instance ()->set_profile (profile->getId ());
  Lobby::instance ()->add_mod (profile->getId ());
  game_scenario->setPlayMode (GameScenario::NETWORKED);
  game_scenario->initialize (g);

  Playerlist::instance ()->syncNeutral ();

  GameServer *game_server = GameServer::instance ();
  if (Lw::app->m_save_server_messages != "")
    game_server->saveMessages (Lw::app->m_save_server_messages);
  game_server->signal_port_in_use ().connect
    ([] (int p)
     {
       std::cerr <<
         String::ucompose (_("%1: couldn't bind to port %2."),
                           Lw::get_prgname (), p) << std::endl;
       Lw::app->quit ();
       exit (1);
     });
  Glib::ustring id = "";

  game_server->start (game_scenario, port, profile->getId (),
                      profile->getNickname ());
  game_server = GameServer::instance ();
  if (game_server->isRunning () == false)
    {
      GameServer::deleteInstance ();
      return;
    }

  std::cout <<
    String::ucompose (_("%1: game server is now listening on port %2."),
                      Lw::get_prgname (), port) << std::endl;
  auto next_turn = new NextTurnNetworked ();
  game_server->signal_round_ends ().connect
    (sigc::mem_fun (*next_turn, &NextTurnNetworked::finishRound));
  game_server->signal_start_player_turn ().connect
    (sigc::mem_fun (*next_turn, &NextTurnNetworked::start_player));
  next_turn->srequestAbort.connect
    (sigc::mem_fun (*game_server, &GameServer::on_turn_aborted));
  game_server->signal_get_next_player ().connect
    (sigc::mem_fun (*next_turn, &NextTurnNetworked::next));

  game_server->signal_countdown ().connect
    ([this, next_turn] (guint32 secs_left)
     {
       if (secs_left == 0)
         next_turn->start ();
     });

  if (mod_first_participant)
    {
      game_server->signal_remote_participant_joins ().connect
        ([] (Glib::ustring mid, bool)
         {
           if (Lobby::instance ()->count_mods () <= 1)
             GameServer::instance ()->add_mod (mid);
         });
    }

  next_turn->m_signal_player_died.connect
    ([] (Player *p, std::shared_ptr<sigc::slot<void()>> after)
     {
       GameServer::instance ()->sendKillPlayer (p);
       if (after)
         (*after) ();
     });
  

  Configuration::s_autosave_policy = Configuration::NO_AUTOSAVING;
  auto game = new Game (game_scenario, next_turn, true);
  game->signal_game_over ().connect
    ([game_scenario] (Player *p, sigc::slot<void()> )
     {
       std::cout <<
         String::ucompose (_("%1: all done!  `%2' was the winner on turn %3."),
                           Lw::get_prgname (), p->getName (),
                           game_scenario->getRound ()) << std::endl;

       GameServer::deleteInstance ();
       exit (0);
     });

}
    
void Startup::start_game_lobby_for_client (Gtk::ApplicationWindow *parent,
                                           GameScenario *game_scenario)
{
  auto game_client = GameClient::instance ();

  game_client->request_seat_manifest ();
  Lobby::instance ()->add_chat_message
    ("", game_scenario->getName ());
  if (game_scenario->getComment () != "")
    Lobby::instance ()->add_chat_message
      ("", game_scenario->getComment ());
  int city_count = Citylist::instance ()->size ();
  int ruin_count = Ruinlist::instance ()->countUnhiddenRuins ();
  int temple_count = Templelist::instance ()->size ();
  Glib::ustring city = ngettext ("city", "cities", city_count);
  Glib::ustring ruin = ngettext ("ruin", "ruins", ruin_count);
  Glib::ustring temple = ngettext ("temple", "temples", temple_count);
  Lobby::instance ()->add_chat_message
    ("",
     String::ucompose
     (_("The scenario has %1 %2, %3 %4 and %5 %6."),
      city_count, city, ruin_count, ruin, temple_count, temple));

  NextTurnNetworked *next_turn = new NextTurnNetworked ();
  // game_client signal_start_player_turn -> next turn start_player
  // happens in game-window

  setup_game_window (false);

  m_game_window->new_network_game (game_scenario, next_turn);

  m_game_window->signal_show_lobby ().connect
    ([this] ()
     {
       m_game_lobby_dialog->show ();
     });

  GameClient::instance ()->signal_game_begin ().connect
    ([this] ()
     {
       m_game_lobby_dialog->set_transient_for (*m_game_window);
       m_game_window->show ();
       m_game_lobby_dialog->set_modal (false);
       m_game_lobby_dialog->hide ();
       m_game_lobby_dialog->start_game ();
       m_signal_game_window_coming_up.emit ();
     });

  m_game_lobby_dialog = LwDialog::build<GameLobbyDialog> (parent);
  m_game_lobby_dialog->setup (game_scenario, false);
  m_game_lobby_dialog->present ();
  m_game_lobby_dialog->signal_response ().connect
    ([this, game_scenario, game_client](Gtk::ResponseType resp)
     {
       if (game_scenario->getRound () == 0)
         {
          switch (resp)
             {
             case Gtk::ResponseType::CANCEL: // either cancel or close
             case Gtk::ResponseType::DELETE_EVENT:
             default:
               m_game_lobby_dialog->hide ();
               game_client->disconnect ();
               GameClient::deleteInstance ();
               break;
             }
         }
     });
}

void Startup::server (Gtk::ApplicationWindow *parent, Profile *profile)
{
}
